@api = http://192.168.1.2:3000/api/trikys

### GET ALL
GET {{api}}/

### GET TRIKYS IN GAME
GET {{api}}/ingame

### CREATE
POST {{api}}/
Content-Type: application/json

{
  "player1": 6
}

### GET BY ID
GET {{api}}/1

### UPDATE BY ID
PATCH {{api}}/3
Content-Type: application/json

{
  "player2": 8
}

### Update Winner Triky
PATCH {{api}}/5
Content-Type: application/json

{
  "user_id":8
}

### DELETE BY ID
DELETE {{api}}/3
