@api = http://192.168.1.2:3000/api/users

### GET ALL
GET {{api}}/

### CREATE
POST {{api}}/
Content-Type: application/json

{
    "name":"Nata Gónzalez Escobar",
    "email":"nata@gmail.com",
    "password": "qaws12pj-22"
}

### CREATE
POST {{api}}/
Content-Type: application/json

{
    "name":"Lina Gomez Moreno",
    "email":"lina@gmail.com",
    "password": "qaws12pj-22"
}

### GET BY ID
GET {{api}}/1

### UPDATE BY ID
PATCH {{api}}/1
Content-Type: application/json

{
    "connected":true
}

### DELETE BY ID
DELETE {{api}}/2


###
POST {{api}}/login
Content-Type: application/json

{
    "email":"sebas@gmail.com",
    "password": "qaws12pj-22"
}

###
GET {{api}}/get/login
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNjczMTEwODMzLCJleHAiOjE2NzMxOTcyMzN9.LLI7vGi1tGqIHECIKESVpTDxFYOCcD1GN8wORUQLzuI
